### PR TITLE
Update ModuleController.php

### PR DESCRIPTION
**Pull request by madaxel**
clear l10n cache after save/update

### CODE REVIEW

**Comment by rrrapha** [comment]
Hi @madaxel
I don't really see the point of this feature. I think 'Clear cache' and 'Edit files' are two different things.

**Comment by madaxel** [comment]
Hi @rrrapha,
I had the feeling that changes in the Backend module won‘t get visible in the frontend before clearing the cache. 
That would be very unuseable for none admin Users. 

Maybe I‘m wrong and changes are directly available in frontend. I Van retest tomorrow.

**Comment by madaxel** [comment]
Hi @rrrapha,
I rechecked and can confirm that without clearing the cache the translation changes will not be visible in frontend.
I use typo3conf/l10n folder to save the translations.

**Comment by rrrapha** [comment]
@maxadel Yes, non admin users cannot clear the cache unless `options.clearCache.all = 1` is set in User TSonfig.
I'll make the automatic cache clearing configurable via extConf..

**Pull request merged**
