### PR TITLE
[CLEANUP] Use inline notation for CSS class definition

### PR DESCRIPTION
**Pull request by liayn**

### CODE REVIEW

**Comment by rrrapha** [comment]
I had this before (see https://github.com/rrrapha/translate_locallang/commit/3d4b2a1feb71e4e70ac342bbeea6a34610521c27), it breaks syntax highlighting in my editor ;)

**Review by rrrapha — APPROVED** [review]

**Comment by liayn** [comment]
Nope, you had something different. take a closer look please.
Your current version breaks phpstorm like completely as it fails to properly detect opening and closing tags.

**Comment by rrrapha** [comment]
I agree that your version looks nicer regardless of any highlight problems of different editors.

**Comment by liayn** [comment]
Well for PHP there is only one serious editor on the market :-P ;-)

**Pull request merged**
